# Generated by Django 2.1.2 on 2018-10-04 18:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='antecedentes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='AntecedentesPatologicos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='examenes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('apellidoPaterno', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='examenes',
            name='pertenece',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='examenes', to='persona.Persona'),
        ),
        migrations.AddField(
            model_name='antecedentespatologicos',
            name='pertenece',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='antecedentespatologiocs', to='persona.Persona'),
        ),
        migrations.AddField(
            model_name='antecedentes',
            name='pertenece',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='antecedentes', to='persona.Persona'),
        ),
    ]
